# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMDBUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=32, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=32, verbose_name='\u7535\u8bdd')),
                ('photo', models.ImageField(upload_to='images', verbose_name='\u7167\u7247')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u7ec4\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Group', verbose_name='\u7ec4id')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u6743\u9650\u540d\u79f0')),
                ('obj_id', models.IntegerField(verbose_name='\u64cd\u4f5c\u5bf9\u8c61')),
                ('description', models.TextField(verbose_name='\u6743\u9650\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Group', verbose_name='\u7ec4id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.CMDBUser', verbose_name='\u7528\u6237id')),
            ],
        ),
        migrations.CreateModel(
            name='User_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Permission', verbose_name='\u6743\u9650id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.CMDBUser', verbose_name='\u7528\u6237id')),
            ],
        ),
        migrations.AddField(
            model_name='group_permission',
            name='permission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Permission', verbose_name='\u6743\u9650id'),
        ),
    ]
